name: Sync Rulesets to SRS

on:
  schedule:
    - cron: '0 2,14 * * *'
  workflow_dispatch:

jobs:
  run-parser:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - run: pip install requests

    - run: |
        LATEST_TAG=$(curl -s https://api.github.com/repos/SagerNet/sing-box/releases/latest | grep '"tag_name":' | sed -E 's/.*"v([^"]+)".*/\1/')
        curl -Lo sing-box.tar.gz "https://github.com/SagerNet/sing-box/releases/download/v${LATEST_TAG}/sing-box-${LATEST_TAG}-linux-amd64.tar.gz"
        tar -xzf sing-box.tar.gz --strip-components=1 "sing-box-${LATEST_TAG}-linux-amd64/sing-box"
        chmod +x sing-box

    - run: python convert.py

    - run: |
        git config --local user.email "actions@github.com"
        git config --local user.name "GitHub Actions"
        
        mkdir -p srs
        git add srs/*.srs 2>/dev/null || true
        
        git diff --staged --quiet || (git commit -m "Auto Update SRS Rulesets" && git push)
